import "./globals.css"
import localFont from "next/font/local"

const monasans = localFont({
  src: "./Mona-Sans.woff2",
  display: "swap",
})

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/favicon.ico",
      type: "image/ico",
    },
    shortcut: { url: "/favicon.ico", type: "image/ico" },
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${monasans.className}`}>{children}</body>
    </html>
  )
}
